pipeline {
    agent any
    stages {
        stage('Example clean') {
            steps {
                sh "rm -rf jenkins-git"
                sh "git clone https://github.com/alexpitronot/jenkins-git.git"                
            }
        }
        stage('Example install') {
            steps {
                sh "mvn install -f jenkins-git"
            }
        }
        stage('Example test') {
            steps {
                sh "mvn test -f jenkins-git"
            }
        }
        stage('Example package') {
            steps {
                sh "mvn package -f jenkins-git"
            }
        }
    }
}