pipeline {
    agent any
    stages {
        stage('Example clean') {
            steps {
                sh "rm -rf jenkins-git"
                sh "git clone https://github.com/alexpitronot/jenkins-git.git"                
            }
        }
        stage('Example install') {
            steps {
                echo 'All Good'
            }
        }
    }
}